[build]
  functions = "netlify/functions"
  publish = "dist"
  command = "npm run build"

[functions]
  node_bundler = "esbuild"

[dev]
  command = "npm run dev"
  targetPort = 5173
  framework = "#custom"