[build]
  functions = "netlify/functions"
  publish = "dist"

[functions]
  # Python runtime for functions
  runtime = "python3.9"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[build.environment]
  # Python dependencies will be installed from requirements.txt in functions directory
  PYTHON_VERSION = "3.9"