services:
  - type: web
    name: suresh-rag-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run rag:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PINECONE_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: PINECONE_INDEX
        sync: false
      - key: PORT
        sync: false
