import { IndustryPageConfig } from "./IndustryPage";

const I = {
  lightning: "M13 10V3L4 14h7v7l9-11h-7z",
  coin: "M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z",
  check: "M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z",
  chart: "M7 12l3-3 3 3 4-4M8 21l4-4 4 4M3 4h18M4 4h16v12a1 1 0 01-1 1H5a1 1 0 01-1-1V4z",
  bars: "M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z",
  star: "M11.049 2.927c.3-.921 1.603-.921 1.902 0l1.519 4.674a1 1 0 00.95.69h4.915c.969 0 1.371 1.24.588 1.81l-3.976 2.888a1 1 0 00-.363 1.118l1.518 4.674c.3.922-.755 1.688-1.538 1.118l-3.976-2.888a1 1 0 00-1.176 0l-3.976 2.888c-.783.57-1.838-.197-1.538-1.118l1.518-4.674a1 1 0 00-.363-1.118l-3.976-2.888c-.784-.57-.38-1.81.588-1.81h4.914a1 1 0 00.951-.69l1.519-4.674z",
};

const img = {
  healthcare: "/image/Portfolio-img/AI-Powered Hospital Management System.png",
  fintech: "/image/pages_img/custom-software-development.png",
  education: "/image/pages_img/Power-AI-Development.png",
  ecommerce: "/image/pages_img/Revolutionize Your Business with Custom Software.png",
  food: "/image/pages_img/Predictive-Analytics-Services.jpg",
  travel: "/image/pages_img/WHY-CHOOSE-US.jpg",
  insurance: "/image/pages_img/ai-automation.jpg",
  ondemand: "/image/pages_img/ai-automation.jpg",
};

export const healthcareConfig: IndustryPageConfig = {
  title: "Healthcare",
  tagline: "Advanced technology for healthcare excellence.",
  heroDescription: "Advanced technology for healthcare excellence.",
  bgImage: img.healthcare,
  professionalTitle: "Intelligent Systems for",
  professionalHighlight: "Healthcare Excellence",
  description1: "We build AI and software systems that help healthcare organizations reduce administrative load, improve care coordination, and operate with more accuracy. From clinical workflows to patient engagement, we design technology around how care is actually delivered.",
  description2: "Our mission is to bring practical, production-ready AI into healthcare so teams can focus on patients instead of paperwork.",
  capabilitiesTitle: "Capabilities and Benefits of",
  capabilitiesHighlight: "AI in Healthcare",
  carouselTitle: "Healthcare AI Solutions",
  carouselSubtitle: "Technology built for better care delivery",
  storiesTitle: "Real-World",
  storiesHighlight: "Healthcare Impact",
  storiesSubtitle: "See how our systems support",
  storiesSubtitleHighlight: "clinical and operational teams",
  faqHighlight: "Healthcare",
  useCases: [
    { id: 1, title: "Clinical Workflow Automation", description: "Reduce documentation time and handoffs with AI that supports intake, notes, and care coordination.", image: img.healthcare, alt: "Clinical Workflow Automation" },
    { id: 2, title: "Intelligent Patient Scheduling", description: "Optimize appointments, reduce no-shows, and match capacity to demand in real time.", image: img.healthcare, alt: "Patient Scheduling" },
    { id: 3, title: "Care Coordination Assistants", description: "Give teams a shared view of patient status, follow-ups, and next actions.", image: img.healthcare, alt: "Care Coordination" },
    { id: 4, title: "Medical Billing Support", description: "Catch coding issues earlier and accelerate reimbursement cycles.", image: img.healthcare, alt: "Medical Billing" },
    { id: 5, title: "Clinical Decision Support", description: "Surface relevant history and risk signals so clinicians can act faster.", image: img.healthcare, alt: "Clinical Decision Support" },
    { id: 6, title: "Patient Engagement Chatbots", description: "Handle routine questions, reminders, and intake 24/7 without adding staff load.", image: img.healthcare, alt: "Patient Chatbots" },
  ],
  capabilities: [
    { icon: I.lightning, title: "Faster Clinical Operations", description: "Automate repetitive admin work so care teams spend more time with patients.", gradient: "from-primary to-accent" },
    { icon: I.coin, title: "Lower Operational Cost", description: "Reduce waste in scheduling, staffing, and billing with systems that learn from your data.", gradient: "from-emerald-500 to-teal-500" },
    { icon: I.check, title: "Better Patient Experience", description: "Shorter wait times, clearer communication, and smoother follow-up journeys.", gradient: "from-primary to-accent" },
    { icon: I.chart, title: "Safer Decision Support", description: "Give clinicians timely context without replacing clinical judgment.", gradient: "from-orange-500 to-red-500" },
    { icon: I.bars, title: "Smarter Resource Planning", description: "Predict demand and staff accordingly across clinics and departments.", gradient: "from-accent to-primary" },
    { icon: I.star, title: "Trusted Delivery", description: "Build systems with security, privacy, and healthcare workflow constraints in mind.", gradient: "from-amber-500 to-yellow-500" },
  ],
  faqData: [
    { id: 1, question: "How can AI help healthcare organizations without disrupting clinicians?", answer: "We start with high-friction workflows such as scheduling, documentation, and follow-ups, then integrate into existing tools so clinicians keep their current process while the busywork decreases." },
    { id: 2, question: "Do you work with clinics as well as larger providers?", answer: "Yes. We design for both small practices and multi-site operations, scaling the same core systems as volume grows." },
    { id: 3, question: "How do you handle patient data security?", answer: "We design around least-privilege access, encryption, auditability, and the privacy requirements of your operating environment." },
    { id: 4, question: "Can this integrate with our current EHR or hospital software?", answer: "Yes. We typically connect through APIs, HL7/FHIR where available, or secure middleware so teams do not need a rip-and-replace." },
    { id: 5, question: "How long does a first healthcare engagement take?", answer: "Most first deployments start with a focused workflow in weeks, then expand once the operational value is proven." },
  ],
};

export const fintechConfig: IndustryPageConfig = {
  title: "Fintech",
  tagline: "Financial technology solutions for modern markets.",
  heroDescription: "Financial technology solutions for modern markets.",
  bgImage: img.fintech,
  professionalTitle: "Secure Intelligence for",
  professionalHighlight: "Modern Finance",
  description1: "We build AI systems for payments, lending, wealth, and financial operations — fraud detection, risk scoring, customer support, and automated back-office workflows that keep pace with modern markets.",
  description2: "Our work helps fintech teams ship faster while staying compliant, auditable, and operationally reliable.",
  capabilitiesTitle: "Capabilities and Benefits of",
  capabilitiesHighlight: "AI in Fintech",
  carouselTitle: "Fintech AI Solutions",
  carouselSubtitle: "Technology for payments, risk, and customer trust",
  storiesTitle: "Real-World",
  storiesHighlight: "Fintech Impact",
  storiesSubtitle: "See how intelligent systems support",
  storiesSubtitleHighlight: "financial products and operations",
  faqHighlight: "Fintech",
  useCases: [
    { id: 1, title: "Fraud Detection", description: "Flag unusual transactions and account behavior in real time before losses compound.", image: img.fintech, alt: "Fraud Detection" },
    { id: 2, title: "Credit & Risk Scoring", description: "Use richer signals to underwrite faster without hiding the decision logic from risk teams.", image: img.fintech, alt: "Risk Scoring" },
    { id: 3, title: "KYC & Onboarding Assistants", description: "Speed up identity checks, document review, and customer onboarding.", image: img.fintech, alt: "KYC Onboarding" },
    { id: 4, title: "Personalized Finance Insights", description: "Help users understand spending, savings, and product fit with clear recommendations.", image: img.fintech, alt: "Finance Insights" },
    { id: 5, title: "Operations Automation", description: "Reduce manual review queues in support, reconciliation, and compliance ops.", image: img.fintech, alt: "Ops Automation" },
    { id: 6, title: "Customer Support Agents", description: "Resolve account questions securely with context from your existing systems.", image: img.fintech, alt: "Support Agents" },
  ],
  capabilities: [
    { icon: I.lightning, title: "Faster Decisioning", description: "Cut review time on onboarding, lending, and support without losing control.", gradient: "from-primary to-accent" },
    { icon: I.coin, title: "Lower Loss Rates", description: "Detect fraud and operational risk earlier with models tuned to your product.", gradient: "from-emerald-500 to-teal-500" },
    { icon: I.check, title: "Better Customer Trust", description: "Clearer journeys, faster answers, and fewer false declines.", gradient: "from-primary to-accent" },
    { icon: I.chart, title: "Audit-Ready Workflows", description: "Keep humans in the loop where regulation and risk require it.", gradient: "from-orange-500 to-red-500" },
    { icon: I.bars, title: "Scalable Back Office", description: "Handle volume spikes without linearly adding operations staff.", gradient: "from-accent to-primary" },
    { icon: I.star, title: "Market-Ready Products", description: "Ship AI features that fit how modern financial products actually operate.", gradient: "from-amber-500 to-yellow-500" },
  ],
  faqData: [
    { id: 1, question: "Can AI be used in regulated financial workflows?", answer: "Yes, when it is designed with human review, logging, and explainability. We do not treat high-risk decisions as fully autonomous by default." },
    { id: 2, question: "Do you integrate with existing cores, CRMs, or payment stacks?", answer: "We connect to the systems you already run and add intelligence around them rather than forcing a platform replacement." },
    { id: 3, question: "How do you approach fraud without blocking good customers?", answer: "We tune for precision, add risk tiers, and keep exception paths for reviewers so legitimate users are not treated as threats." },
    { id: 4, question: "What does a first fintech project usually look like?", answer: "A tightly scoped workflow such as transaction review, KYC document handling, or support deflection, then expansion after measured results." },
    { id: 5, question: "How is customer financial data protected?", answer: "Access is limited, data is encrypted in transit and at rest, and we follow the security requirements of your environment and partners." },
  ],
};

export const educationConfig: IndustryPageConfig = {
  title: "Education",
  tagline: "We promote education through innovative technology.",
  heroDescription: "We promote education through innovative technology.",
  bgImage: img.education,
  professionalTitle: "Learning Systems Built for",
  professionalHighlight: "Modern Education",
  description1: "We help schools, EdTech companies, and training organizations use AI for personalized learning, student support, content operations, and administrative automation.",
  description2: "The goal is simple: better learning outcomes with less operational friction for teachers, students, and staff.",
  capabilitiesTitle: "Capabilities and Benefits of",
  capabilitiesHighlight: "AI in Education",
  carouselTitle: "Education AI Solutions",
  carouselSubtitle: "Technology that supports teaching and learning",
  storiesTitle: "Real-World",
  storiesHighlight: "Education Impact",
  storiesSubtitle: "See how institutions use AI to",
  storiesSubtitleHighlight: "improve learning operations",
  faqHighlight: "Education",
  useCases: [
    { id: 1, title: "Personalized Learning Paths", description: "Adapt content and practice to each learner’s pace, gaps, and goals.", image: img.education, alt: "Personalized Learning" },
    { id: 2, title: "Tutoring Assistants", description: "Give students 24/7 help that stays aligned with your curriculum.", image: img.education, alt: "Tutoring Assistants" },
    { id: 3, title: "Teacher Workflow Support", description: "Draft lesson materials, quizzes, and feedback without replacing the teacher.", image: img.education, alt: "Teacher Support" },
    { id: 4, title: "Admissions & Student Ops", description: "Automate repetitive questions, document collection, and status updates.", image: img.education, alt: "Student Operations" },
    { id: 5, title: "Assessment Analytics", description: "Spot learning gaps earlier with clearer views of progress and risk.", image: img.education, alt: "Assessment Analytics" },
    { id: 6, title: "Campus Support Chatbots", description: "Answer policy, schedule, and campus questions instantly.", image: img.education, alt: "Campus Chatbots" },
  ],
  capabilities: [
    { icon: I.lightning, title: "More Teaching Time", description: "Take routine content and admin work off teachers’ plates.", gradient: "from-primary to-accent" },
    { icon: I.coin, title: "Lower Support Cost", description: "Deflect repetitive student and parent questions with accurate assistants.", gradient: "from-emerald-500 to-teal-500" },
    { icon: I.check, title: "Better Learner Outcomes", description: "Personalize practice and feedback without adding headcount.", gradient: "from-primary to-accent" },
    { icon: I.chart, title: "Clearer Progress Insight", description: "See who is falling behind and intervene earlier.", gradient: "from-orange-500 to-red-500" },
    { icon: I.bars, title: "Scalable Programs", description: "Serve more learners with consistent quality across cohorts.", gradient: "from-accent to-primary" },
    { icon: I.star, title: "Safe Learning Environments", description: "Design with content controls, privacy, and age-appropriate guardrails.", gradient: "from-amber-500 to-yellow-500" },
  ],
  faqData: [
    { id: 1, question: "Will AI replace teachers?", answer: "No. We build tools that support teachers — drafting, tutoring, and operations — while humans stay in control of instruction and assessment." },
    { id: 2, question: "Can this work with our LMS or student information system?", answer: "Yes. We integrate with common education platforms and internal databases so faculty do not have to change every tool they use." },
    { id: 3, question: "How do you keep student data private?", answer: "We minimize collected data, restrict access, and follow the privacy rules required by your institution." },
    { id: 4, question: "Is this useful for corporate training as well as schools?", answer: "Yes. The same pattern works for universities, K-12 operators, and workplace learning programs." },
    { id: 5, question: "How quickly can we launch a first assistant?", answer: "A curriculum-grounded Q&A or admin assistant can often go live as a focused pilot within weeks." },
  ],
};

export const ecommerceConfig: IndustryPageConfig = {
  title: "E-Commerce",
  tagline: "We enhance online commerce with tailored solutions.",
  heroDescription: "We enhance online commerce with tailored solutions.",
  bgImage: img.ecommerce,
  professionalTitle: "Conversion Systems for",
  professionalHighlight: "Online Commerce",
  description1: "We help retailers and marketplaces increase conversion, reduce returns, and run operations with less manual work — from recommendations and search to support, inventory, and fulfillment intelligence.",
  description2: "Every build is tailored to your catalog, channels, and customer journey rather than a generic storefront add-on.",
  capabilitiesTitle: "Capabilities and Benefits of",
  capabilitiesHighlight: "AI in E-Commerce",
  carouselTitle: "E-Commerce AI Solutions",
  carouselSubtitle: "Technology that turns traffic into revenue",
  storiesTitle: "Real-World",
  storiesHighlight: "Commerce Impact",
  storiesSubtitle: "See how brands use AI to",
  storiesSubtitleHighlight: "grow and operate online stores",
  faqHighlight: "E-Commerce",
  useCases: [
    { id: 1, title: "Product Recommendations", description: "Show the right product at the right moment using behavior, inventory, and context.", image: img.ecommerce, alt: "Recommendations" },
    { id: 2, title: "Intelligent Search", description: "Help shoppers find items with natural language, typo tolerance, and intent.", image: img.ecommerce, alt: "Commerce Search" },
    { id: 3, title: "Shopping Assistants", description: "Guide customers through size, fit, and product questions in real time.", image: img.ecommerce, alt: "Shopping Assistants" },
    { id: 4, title: "Demand Forecasting", description: "Plan inventory and promotions with more accurate demand signals.", image: img.ecommerce, alt: "Demand Forecasting" },
    { id: 5, title: "Returns Reduction", description: "Improve product guidance and QA so fewer orders come back.", image: img.ecommerce, alt: "Returns Reduction" },
    { id: 6, title: "Store Operations Automation", description: "Automate catalog updates, support tickets, and order exception handling.", image: img.ecommerce, alt: "Store Ops" },
  ],
  capabilities: [
    { icon: I.lightning, title: "Higher Conversion", description: "Make discovery, search, and checkout easier with relevant recommendations.", gradient: "from-primary to-accent" },
    { icon: I.coin, title: "Better Margin", description: "Reduce overstock, stockouts, and costly returns with predictive operations.", gradient: "from-emerald-500 to-teal-500" },
    { icon: I.check, title: "Richer Customer Experience", description: "Answer product questions instantly and personalize the path to purchase.", gradient: "from-primary to-accent" },
    { icon: I.chart, title: "Clearer Merchandising Insight", description: "See what actually drives demand across SKUs, channels, and campaigns.", gradient: "from-orange-500 to-red-500" },
    { icon: I.bars, title: "Leaner Operations", description: "Handle catalog, support, and fulfillment exceptions without adding headcount at the same rate.", gradient: "from-accent to-primary" },
    { icon: I.star, title: "Tailored to Your Stack", description: "Works with Shopify, custom storefronts, ERPs, and the tools you already run.", gradient: "from-amber-500 to-yellow-500" },
  ],
  faqData: [
    { id: 1, question: "Do you only work with large marketplaces?", answer: "No. We work with growing D2C brands, retailers, and marketplaces. The first build is scoped to the highest-friction part of the funnel." },
    { id: 2, question: "Can this connect to Shopify or a custom storefront?", answer: "Yes. We integrate with common commerce platforms, PIMs, ERPs, and custom stacks." },
    { id: 3, question: "How soon can recommendations or search improve?", answer: "If catalog and event data are available, a first recommendation or search improvement can be launched as a controlled experiment quickly." },
    { id: 4, question: "Will this replace our current support team?", answer: "It reduces repetitive tickets. Complex orders, exceptions, and VIP cases still go to people." },
    { id: 5, question: "How do you measure success?", answer: "We agree on conversion, AOV, ticket volume, forecast error, or return rate before build — then instrument those outcomes." },
  ],
};

export const foodGroceriesConfig: IndustryPageConfig = {
  title: "Food & Groceries",
  tagline: "Tech solutions revolutionizing food and grocery.",
  heroDescription: "Tech solutions revolutionizing food and grocery.",
  bgImage: img.food,
  professionalTitle: "Operational Intelligence for",
  professionalHighlight: "Food & Grocery",
  description1: "We help grocery, QSR, delivery, and food brands forecast demand, reduce waste, personalize offers, and run stores and kitchens with fewer manual processes.",
  description2: "The result is fresher inventory, better availability, and operations that keep up with daily demand swings.",
  capabilitiesTitle: "Capabilities and Benefits of",
  capabilitiesHighlight: "AI in Food & Grocery",
  carouselTitle: "Food & Grocery AI Solutions",
  carouselSubtitle: "Technology for availability, waste, and speed",
  storiesTitle: "Real-World",
  storiesHighlight: "Grocery Impact",
  storiesSubtitle: "See how food businesses use AI to",
  storiesSubtitleHighlight: "run smarter daily operations",
  faqHighlight: "Food & Groceries",
  useCases: [
    { id: 1, title: "Demand & Freshness Forecasting", description: "Predict what will sell before it spoils or sits on the shelf.", image: img.food, alt: "Demand Forecasting" },
    { id: 2, title: "Inventory Optimization", description: "Keep high-velocity SKUs in stock without over-ordering perishable items.", image: img.food, alt: "Inventory Optimization" },
    { id: 3, title: "Personalized Offers", description: "Recommend products and promotions based on local demand and customer habits.", image: img.food, alt: "Personalized Offers" },
    { id: 4, title: "Kitchen & Store Workflow", description: "Coordinate prep, staffing, and replenishment around real demand.", image: img.food, alt: "Store Workflow" },
    { id: 5, title: "Quality & Safety Support", description: "Flag process exceptions and documentation gaps before they become incidents.", image: img.food, alt: "Quality Support" },
    { id: 6, title: "Customer Ordering Assistants", description: "Help shoppers reorder, substitute, and resolve delivery issues faster.", image: img.food, alt: "Ordering Assistants" },
  ],
  capabilities: [
    { icon: I.lightning, title: "Less Waste", description: "Match ordering and prep to predicted demand instead of guesswork.", gradient: "from-primary to-accent" },
    { icon: I.coin, title: "Better Availability", description: "Reduce stockouts on the items customers actually come for.", gradient: "from-emerald-500 to-teal-500" },
    { icon: I.check, title: "Faster Store Operations", description: "Give staff a clearer daily plan for replenishment and prep.", gradient: "from-primary to-accent" },
    { icon: I.chart, title: "Local Demand Insight", description: "See what changes by store, day, weather, and promotion.", gradient: "from-orange-500 to-red-500" },
    { icon: I.bars, title: "Smarter Promotions", description: "Push offers that clear inventory without destroying margin.", gradient: "from-accent to-primary" },
    { icon: I.star, title: "Built for Daily Rhythm", description: "Designed around perishable inventory and high-frequency operations.", gradient: "from-amber-500 to-yellow-500" },
  ],
  faqData: [
    { id: 1, question: "Do we need perfect historical data to start?", answer: "No. We start with the data you have — POS, inventory, and orders — then improve forecasts as more history accumulates." },
    { id: 2, question: "Can this work for both grocery retail and foodservice?", answer: "Yes. The same demand and operations patterns apply to stores, dark kitchens, and multi-location QSRs." },
    { id: 3, question: "How do you handle substitutions and delivery issues?", answer: "We can add assistants and rules that suggest substitutes, notify customers, and route exceptions to staff." },
    { id: 4, question: "Will store teams have to learn a new system?", answer: "We usually embed recommendations into the tools teams already use, with a simple daily view rather than a complex new dashboard." },
    { id: 5, question: "What is the first use case most grocers start with?", answer: "Fresh-item demand forecasting or stockout reduction, because the ROI is visible in waste and availability within a short cycle." },
  ],
};

export const travelTourismConfig: IndustryPageConfig = {
  title: "Travel & Tourism",
  tagline: "Digital solutions for travel and hospitality.",
  heroDescription: "Digital solutions for travel and hospitality.",
  bgImage: img.travel,
  professionalTitle: "Guest Experience Systems for",
  professionalHighlight: "Travel & Hospitality",
  description1: "We build AI for hotels, travel operators, and tourism brands — booking assistants, dynamic operations, guest support, and revenue tools that keep journeys smooth from search to stay.",
  description2: "The focus is practical: fewer manual tickets, better occupancy decisions, and guests who get answers immediately.",
  capabilitiesTitle: "Capabilities and Benefits of",
  capabilitiesHighlight: "AI in Travel & Tourism",
  carouselTitle: "Travel & Hospitality AI Solutions",
  carouselSubtitle: "Technology for bookings, guests, and operations",
  storiesTitle: "Real-World",
  storiesHighlight: "Hospitality Impact",
  storiesSubtitle: "See how travel brands use AI to",
  storiesSubtitleHighlight: "serve guests and run properties",
  faqHighlight: "Travel & Tourism",
  useCases: [
    { id: 1, title: "Booking Assistants", description: "Help travelers compare, book, and change itineraries in natural language.", image: img.travel, alt: "Booking Assistants" },
    { id: 2, title: "Guest Support 24/7", description: "Answer stay questions, amenity requests, and policy issues instantly.", image: img.travel, alt: "Guest Support" },
    { id: 3, title: "Dynamic Pricing Support", description: "Give revenue teams better demand signals for rooms, packages, and dates.", image: img.travel, alt: "Dynamic Pricing" },
    { id: 4, title: "Operations Coordination", description: "Connect housekeeping, front desk, and vendor workflows around occupancy.", image: img.travel, alt: "Hotel Operations" },
    { id: 5, title: "Personalized Offers", description: "Recommend experiences, upgrades, and packages based on traveler intent.", image: img.travel, alt: "Personalized Offers" },
    { id: 6, title: "Disruption Handling", description: "Reroute, rebook, and communicate faster when plans change.", image: img.travel, alt: "Disruption Handling" },
  ],
  capabilities: [
    { icon: I.lightning, title: "Faster Bookings", description: "Reduce drop-off by answering trip questions at the moment of intent.", gradient: "from-primary to-accent" },
    { icon: I.coin, title: "Stronger Revenue", description: "Support pricing, upsell, and occupancy decisions with live demand context.", gradient: "from-emerald-500 to-teal-500" },
    { icon: I.check, title: "Better Guest Satisfaction", description: "Give travelers immediate answers instead of waiting on a queue.", gradient: "from-primary to-accent" },
    { icon: I.chart, title: "Clearer Demand Visibility", description: "See booking patterns and operational load before they hit the front desk.", gradient: "from-orange-500 to-red-500" },
    { icon: I.bars, title: "Leaner Property Ops", description: "Coordinate staff and vendors around real occupancy, not static schedules.", gradient: "from-accent to-primary" },
    { icon: I.star, title: "Built for Hospitality", description: "Designed around seasons, cancellations, and high-volume guest communication.", gradient: "from-amber-500 to-yellow-500" },
  ],
  faqData: [
    { id: 1, question: "Can this connect to our PMS, CRS, or booking engine?", answer: "Yes. We integrate with property, reservation, and CRM systems so guest answers stay accurate." },
    { id: 2, question: "Will the assistant invent hotel policies?", answer: "No. We ground responses in your approved content and escalate when the answer is not in source material." },
    { id: 3, question: "Is this useful for OTAs as well as hotels?", answer: "Yes. The same patterns apply to operators, OTAs, destination brands, and multi-property groups." },
    { id: 4, question: "How do you handle peak season volume?", answer: "Assistants absorb repetitive questions so staff can focus on exceptions, VIPs, and on-property issues." },
    { id: 5, question: "What is a typical first project?", answer: "A guest FAQ and booking-change assistant, because it reduces tickets quickly and proves the workflow." },
  ],
};

export const insuranceConfig: IndustryPageConfig = {
  title: "Insurance",
  tagline: "Innovative insurance technology solutions.",
  heroDescription: "Innovative insurance technology solutions.",
  bgImage: img.insurance,
  professionalTitle: "Claims and Underwriting Systems for",
  professionalHighlight: "Modern Insurance",
  description1: "We help insurers and MGAs automate intake, underwriting support, claims handling, fraud review, and customer communication without losing control of risk decisions.",
  description2: "The result is faster cycle times, fewer manual touches, and a clearer audit trail.",
  capabilitiesTitle: "Capabilities and Benefits of",
  capabilitiesHighlight: "AI in Insurance",
  carouselTitle: "Insurance AI Solutions",
  carouselSubtitle: "Technology for claims, underwriting, and service",
  storiesTitle: "Real-World",
  storiesHighlight: "Insurance Impact",
  storiesSubtitle: "See how carriers use AI to",
  storiesSubtitleHighlight: "move work faster with control",
  faqHighlight: "Insurance",
  useCases: [
    { id: 1, title: "Claims Intake Automation", description: "Capture FNOL details, documents, and photos with less back-and-forth.", image: img.insurance, alt: "Claims Intake" },
    { id: 2, title: "Underwriting Assistants", description: "Summarize submissions and flag missing data for underwriters.", image: img.insurance, alt: "Underwriting Assistants" },
    { id: 3, title: "Fraud & Anomaly Review", description: "Surface unusual claim patterns for investigators instead of sampling everything.", image: img.insurance, alt: "Fraud Review" },
    { id: 4, title: "Policyholder Support", description: "Answer coverage, billing, and status questions with grounded policy content.", image: img.insurance, alt: "Policyholder Support" },
    { id: 5, title: "Document Intelligence", description: "Extract and classify medical, legal, and policy documents at scale.", image: img.insurance, alt: "Document Intelligence" },
    { id: 6, title: "Workflow Routing", description: "Send each case to the right queue based on complexity and risk.", image: img.insurance, alt: "Workflow Routing" },
  ],
  capabilities: [
    { icon: I.lightning, title: "Shorter Cycle Times", description: "Move intake, review, and communication faster without skipping controls.", gradient: "from-primary to-accent" },
    { icon: I.coin, title: "Lower Loss Adjustment Expense", description: "Reduce repetitive handling on straightforward claims and submissions.", gradient: "from-emerald-500 to-teal-500" },
    { icon: I.check, title: "Better Customer Experience", description: "Give policyholders status and answers without waiting on a call center.", gradient: "from-primary to-accent" },
    { icon: I.chart, title: "Stronger Risk Control", description: "Keep humans on high-severity decisions while AI prepares the file.", gradient: "from-orange-500 to-red-500" },
    { icon: I.bars, title: "Clearer Work Queues", description: "Route simple vs. complex work so specialists spend time where it matters.", gradient: "from-accent to-primary" },
    { icon: I.star, title: "Audit-Friendly Design", description: "Log sources, decisions, and overrides so compliance teams can review.", gradient: "from-amber-500 to-yellow-500" },
  ],
  faqData: [
    { id: 1, question: "Will AI make final underwriting or claims decisions?", answer: "Not by default. We typically prepare files, extract facts, and recommend next steps while licensed staff make the decision." },
    { id: 2, question: "Can this work with our core policy and claims systems?", answer: "Yes. We integrate through APIs, document stores, and workflow tools already in use." },
    { id: 3, question: "How do you keep answers aligned with policy wording?", answer: "Customer-facing assistants are grounded in approved documents and escalate when the answer is not explicit." },
    { id: 4, question: "Is this only for P&C, or also health and life?", answer: "The same intake, document, and workflow patterns apply across P&C, health, life, and specialty lines." },
    { id: 5, question: "What should we automate first?", answer: "FNOL intake or submission summarization, because those create immediate time savings for adjusters and underwriters." },
  ],
};

export const onDemandConfig: IndustryPageConfig = {
  title: "On-Demand",
  tagline: "Instant solutions tailored to your needs.",
  heroDescription: "Instant solutions tailored to your needs.",
  bgImage: img.ondemand,
  professionalTitle: "Matching and Dispatch Systems for",
  professionalHighlight: "On-Demand Services",
  description1: "We build AI for on-demand platforms — dispatch, matching, support, pricing signals, and operations dashboards that keep supply and demand aligned in real time.",
  description2: "Whether you run mobility, delivery, home services, or staffing, the system is tailored to how your marketplace actually moves.",
  capabilitiesTitle: "Capabilities and Benefits of",
  capabilitiesHighlight: "AI in On-Demand",
  carouselTitle: "On-Demand AI Solutions",
  carouselSubtitle: "Technology for matching, dispatch, and support",
  storiesTitle: "Real-World",
  storiesHighlight: "Marketplace Impact",
  storiesSubtitle: "See how on-demand platforms use AI to",
  storiesSubtitleHighlight: "move faster with less chaos",
  faqHighlight: "On-Demand",
  useCases: [
    { id: 1, title: "Intelligent Dispatch", description: "Match jobs to the right provider based on location, skill, SLA, and live load.", image: img.ondemand, alt: "Intelligent Dispatch" },
    { id: 2, title: "Demand Prediction", description: "Anticipate spikes so you can staff, position, and price before the surge hits.", image: img.ondemand, alt: "Demand Prediction" },
    { id: 3, title: "Customer Support Agents", description: "Resolve order, ETA, and cancellation questions without flooding ops.", image: img.ondemand, alt: "Support Agents" },
    { id: 4, title: "Provider Performance Insights", description: "Spot reliability issues and coaching opportunities across your supply.", image: img.ondemand, alt: "Provider Insights" },
    { id: 5, title: "Exception Handling", description: "Route failed jobs, no-shows, and disputes to the right playbook automatically.", image: img.ondemand, alt: "Exception Handling" },
    { id: 6, title: "Ops Command Assistants", description: "Give operators a live view of bottlenecks and recommended next actions.", image: img.ondemand, alt: "Ops Assistants" },
  ],
  capabilities: [
    { icon: I.lightning, title: "Faster Fulfillment", description: "Cut the time between request and assignment with better matching.", gradient: "from-primary to-accent" },
    { icon: I.coin, title: "Higher Utilization", description: "Keep providers busy on the right jobs instead of idle or overloaded.", gradient: "from-emerald-500 to-teal-500" },
    { icon: I.check, title: "Better Customer Reliability", description: "Fewer missed ETAs and clearer communication when something changes.", gradient: "from-primary to-accent" },
    { icon: I.chart, title: "Live Marketplace Insight", description: "See demand, supply, and exceptions as they happen.", gradient: "from-orange-500 to-red-500" },
    { icon: I.bars, title: "Leaner Ops Teams", description: "Automate the repetitive tickets so operators handle true exceptions.", gradient: "from-accent to-primary" },
    { icon: I.star, title: "Tailored to Your Model", description: "Built around your SLAs, zones, skills, and how work actually gets done.", gradient: "from-amber-500 to-yellow-500" },
  ],
  faqData: [
    { id: 1, question: "Can this work if our marketplace is still early?", answer: "Yes. We start with dispatch rules and support automation, then add prediction as volume grows." },
    { id: 2, question: "Do you replace our existing app?", answer: "Usually no. We add intelligence to dispatch, support, and ops around the product you already have." },
    { id: 3, question: "How do you keep matching fair and explainable?", answer: "We encode your rules — skills, zones, SLAs, seniority — and make assignment reasons visible to ops." },
    { id: 4, question: "What about last-minute cancellations and no-shows?", answer: "Exception playbooks can reassign, notify, and escalate automatically instead of relying on a busy ops chat." },
    { id: 5, question: "How fast can a first dispatch or support assistant launch?", answer: "A focused support or routing assistant can often be piloted in weeks once we have job and location data." },
  ],
};
